# Lecture 2: operations

http://web.stanford.edu/class/cs20si/lectures/slides_02.pdf

all imports

In [1]:
import tensorflow as tf
from util import Example


## The first example perform a basic addiction between two scalars 

In [6]:
class Basic1(Example):

    def graphsession(self):
        graph = tf.Graph() 
        with graph.as_default():
            a = tf.constant(222, name="A")
            b = tf.constant(3222, name="B")
            x = tf.add(a, b, name="sum")
        with tf.Session(graph=graph) as sess:
            writer = tf.summary.FileWriter(self.log_path, sess.graph)
            print(sess.run(x))
            
ex1 = Basic1()


3444


In [7]:
ex1.log_path

'./graphs/03-03-2017_15-10-00'

### Running the following commmad we now can see the graph at http://127.0.1.1:8008


In [8]:
#!tensorboard --logdir=./graphs/03-03-2017_15-10-00 --port=8008
#os.system("tensorboard --logdir=" + ex1.log_path)

Starting TensorBoard b'41' on port 8008
(You can navigate to http://127.0.1.1:8008)
^C
Traceback (most recent call last):
  File "/home/felsal/workenv/bin/tensorboard", line 11, in <module>
    sys.exit(main())
  File "/home/felsal/workenv/lib/python3.5/site-packages/tensorflow/tensorboard/tensorboard.py", line 151, in main
    tb_server.serve_forever()
  File "/usr/lib/python3.5/socketserver.py", line 232, in serve_forever
    ready = selector.select(poll_interval)
  File "/usr/lib/python3.5/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)
KeyboardInterrupt


## Addiction and multiplication with tensors 

In [5]:
class Basic2(Example):

    def graphsession(self):
        graph = tf.Graph() 
        with graph.as_default():
            a = tf.constant([2, 2], name="a")
            b = tf.constant([[0, 1],[0, 1]], name="b")
            x = tf.add(a, b, name="add")
            y = tf.multiply(a, b, name="mul")
        with tf.Session(graph=graph) as sess:
            writer = tf.summary.FileWriter(self.log_path, sess.graph)
            x, y = sess.run([x, y])
            print(x)
            print("\n",y)
            
            
ex2 = Basic2()

[[2 3]
 [2 3]]

 [[0 2]
 [0 2]]


In [6]:
ex2.log_path

'./graphs/01-03-2017_22-03-13'

In [7]:
# !tensorboard --logdir=./graphs/01-03-2017_20-37-24 --port=8008
#os.system("tensorboard --logdir=" + ex1.log_path)

# Tensors with values 
- tf.zeros : creates a tensor of shape and all elements will be zeros (when ran in session)
- tf.zeros_like : creates a tensor of shape and type (unless type is specified) as the input_tensor but all elements are zeros.
- tf.ones :  similar as above but with 1.
- tf.ones_like : similar as above but with 1.
- tf.fill : creates a tensor filled with a scalar value

In [6]:
class Basic3(Example):

    def graphsession(self):
        graph = tf.Graph() 
        with graph.as_default():
            zeros1 = tf.zeros([2, 3], tf.int32, name="zeros1") 
            input_tensor = tf.constant([[0, 1],[0, 1]], name="input")
            zeros2 = tf.zeros_like(input_tensor, name="zeros2")
            ones1 = tf.ones([2, 3], tf.int32, name="ones1") 
            ones2 = tf.ones_like(input_tensor, name="ones2")
            only69 = tf.fill([2, 3], 69,name="only69") 
        with tf.Session(graph=graph) as sess:
            writer = tf.summary.FileWriter(self.log_path, sess.graph)
            x1,x2,x3,x4,x5 = sess.run([zeros1,
                             zeros2,
                             ones1,
                             ones2,
                             only69])
            print(x1)
            print("\n",x2)
            print("\n",x3)
            print("\n",x4)
            print("\n",x5)
            
            
ex3 = Basic3()

[[0 0 0]
 [0 0 0]]

 [[0 0]
 [0 0]]

 [[1 1 1]
 [1 1 1]]

 [[1 1]
 [1 1]]

 [[69 69 69]
 [69 69 69]]


# Constants as sequences
- tf.linspace : Generates values in an interval.
- tf.range : Creates a sequence of numbers.

** Tensor objects are not iterable **

In [9]:
class Basic4(Example):

    def graphsession(self):
        graph = tf.Graph() 
        with graph.as_default():
            seq1 = tf.linspace(10.0, 19.0, 4)
            seq2 = tf.range(10, 19, 2.6) 
        with tf.Session(graph=graph) as sess:
            writer = tf.summary.FileWriter(self.log_path, sess.graph)
            x1, x2 = sess.run([seq1,seq2])
            print(x1)
            print("\n",x2)

            
ex4 = Basic4()

[ 10.  13.  16.  19.]

 [ 10.          12.60000038  15.20000076  17.80000114]


# Variables

**Why tf.constant but tf.Variable and not
tf.variable?**
tf.Variable is a class, but tf.constant is an op

We use **tf.global_variables_initializer()** to initialize all variables.

But we can also initialize only a subset of variables using **tf.variables_initializer**

Or initialaze a single variable using the method **initializer**

In [10]:
class Basic5(Example):

    def graphsession(self):
        graph = tf.Graph() 
        with graph.as_default():
            # create variable a with scalar value
            a = tf.Variable(2, name="scalar")
            # create variable b as a vector
            b = tf.Variable([2, 3], name="vector")
            # create variable c as a 2x2 matrix
            c = tf.Variable([[0, 1], [2, 3]], name="matrix")
            # create variable W as 784 x 10 tensor, filled with zeros
            W = tf.Variable(tf.zeros([784,10]))
            init = tf.global_variables_initializer()
            # init_ab = tf.variables_initializer([a, b], name="init_ab")
        with tf.Session(graph=graph) as sess:
            writer = tf.summary.FileWriter(self.log_path, sess.graph)
            sess.run(init)
            # sess.run(init_ab)
            # sess.run(W.initializer)
            x1, x2, x3, x4 = sess.run([a,b,c,W])
            print(x1)
            print("\n",x2)
            print("\n",x3)
            print("\n",x4)

            
ex5 = Basic5()

2

 [2 3]

 [[0 1]
 [2 3]]

 [[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]]


**We can also evaluate a variable using the method eval()**

In [11]:
class Basic6(Example):

    def graphsession(self):
        graph = tf.Graph() 
        with graph.as_default():
            # W is a random 700 x 100 variable object
            W = tf.Variable(tf.truncated_normal([700, 10]))
        with tf.Session(graph=graph) as sess:
            sess.run(W.initializer)
            print(W.eval())

            
ex6 = Basic6()

[[ 0.84076756 -0.90812659 -0.47966206 ...,  1.12063146  0.27350563
  -1.74830937]
 [ 0.77990538 -0.91419172 -0.86873174 ...,  0.82648492  0.56310332
   0.59445041]
 [ 0.55119783  0.92487913 -0.31647921 ..., -0.0327384   1.56877339
  -0.22373645]
 ..., 
 [-0.80001235  0.28308502  0.22478563 ...,  0.56657737  0.88197315
  -1.30233169]
 [ 0.57932097  0.91847676  1.05598235 ...,  0.20412961  0.71497482
  -1.5133673 ]
 [ 0.66313416 -0.32703808 -0.97717941 ...,  1.62078166  0.2557348
   0.04032356]]


**assign(), assign_add() and assign_sub() are methods to assign values to a variable, this operation needs to be run to take effect**

In [12]:
class Basic7(Example):

    def graphsession(self):
        graph = tf.Graph() 
        with graph.as_default():
            W = tf.Variable(10.)
            assign_op = W.assign(20 * W + 2.2)
        with tf.Session(graph=graph) as sess:
            sess.run(W.initializer)
            print(W.eval())
            sess.run(assign_op)
            print(W.eval())
            sess.run(assign_op)
            print(W.eval())
            sess.run(W.assign_add(1000.)) 
            print(W.eval())
            sess.run(W.assign_sub(2000.)) 
            print(W.eval())
        with tf.Session(graph=graph) as sess:
            sess.run(W.initializer)
            print(W.eval())
ex7 = Basic7()

10.0
202.2
4046.2
5046.2
3046.2
10.0


** Each session maintains its own copy of
variable **

In [14]:
class Basic8(Example):

    def graphsession(self):
        graph = tf.Graph() 
        with graph.as_default():
            W = tf.Variable(10.)
        with tf.Session(graph=graph) as sess:
            sess.run(W.initializer)
            print(W.eval())
            sess.run(W.assign_add(2.)) 
            print(W.eval())
        print(" ")
        with tf.Session(graph=graph) as sess:
            sess.run(W.initializer)
            print(W.eval())
            sess.run(W.assign_sub(2.)) 
            print(W.eval())
ex8 = Basic8()

10.0
12.0
 
10.0
8.0


# Session vs InteractiveSession
You sometimes see InteractiveSession instead of Session
The only difference is an InteractiveSession makes itself the default

In [7]:
sess = tf.InteractiveSession()
a = tf.constant(5.0)
b = tf.constant(6.0)
c = a * b
# We can just use 'c.eval()' without specifying the context 'sess'
print(c.eval())
sess.close()

30.0


# Placeholders

** Why placeholders?**
We, or our clients, can later supply their own data when they need to execute the computation. 


**Quirk:**
- shape=None means that tensor of any shape will be accepted as value for  placeholder.
- shape=None is easy to construct graphs, but nightmarish for debugging
-  shape=None also breaks all following  shape inference, which makes many ops not work because they expect certain rank

## You can feed_dict any feedable tensor. Placeholder is just a way to indicate that something must be fed

In [13]:
class Basic9(Example):

    def graphsession(self):
        graph = tf.Graph() 
        with graph.as_default():
            # create a placeholder of type float 32-bit, shape is a vector of 3 elements
            a = tf.placeholder(tf.float32, shape=[3])
            # create a constant of type float 32-bit, shape is a vector of 3 elements
            b = tf.constant([5, 5, 5], tf.float32)
            # use the placeholder as you would a constant or a variable
            c = a + b # Short for tf.add(a, b)
        with tf.Session(graph=graph) as sess:
            all_dict = {0:{a: [1, 2, 3]}, 1:{a: [1, 2, 3], b:[1, 2, 3]}}
            for i in [0,1]:
                feed_dict = all_dict[i]
                result = sess.run(c,feed_dict=feed_dict)
                print(result)

ex9 = Basic9()

[ 6.  7.  8.]
[ 2.  4.  6.]


# Lazy loading

## Lazy loading = Defer creating/initializing an object until it is needed

As you can see in the examples 10 and 11, the result is the same. But in Basic10 the  add node is already on the graph and in Basic 11 the node add is added 5 times to the graph 
definition. **As a result your graph gets bloated, slow to load and expensive to pass around.**

**Solution**

1. Separate definition of ops from computing/running ops 
2. Use Python property to ensure function is also loaded once the first time it is called



In [20]:
class Basic10(Example):

    def graphsession(self):
        graph = tf.Graph() 
        with graph.as_default():
            x = tf.Variable(10, name='x')
            y = tf.Variable(20, name='y')
            z = tf.add(x, y) # you create the node for add node before executing the graph
        with tf.Session(graph=graph) as sess:
            sess.run(tf.global_variables_initializer())
            writer = tf.summary.FileWriter(self.log_path, sess.graph)
            for _ in range(5):
                print(sess.run(z))
                writer.close()

ex10 = Basic10()

30
30
30
30
30


In [23]:
class Basic11(Example):

    def graphsession(self):
        graph = tf.Graph() 
        with graph.as_default():
            x = tf.Variable(10, name='x')
            y = tf.Variable(20, name='y')
        with tf.Session(graph=graph) as sess:
            sess.run(tf.global_variables_initializer())
            writer = tf.summary.FileWriter(self.log_path, sess.graph)
            for _ in range(5):
                print(sess.run(tf.add(x, y)))
                writer.close()

ex11 = Basic11()

30
30
30
30
30
